version: '.0'

services:
  ros2_x11:
    image: r1_foxy_from_file:latest  
    container_name: ros2_foxy_2
    environment:
      - DISPLAY=host.docker.internal:0.0
      # - DISPLAY=$DISPLAY
    volumes:
      # - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - E:\E_Data\git\ros2_ws:/home/ros2_ws/ws_1
    # user: pravaig
    #user: "$(id -u):$(id -g)" 
    # environment:
    # - HOST_UID=1000
    command: 
    # - "chown -R ${HOST_UID}:${HOST_UID} /home/ros_ws/"
    - bash
    tty: true
    stdin_open: true

    # docker run --name ros2_foxy -e DISPLAY=host.docker.internal:0.0 -it osrf/ros:foxy-desktop
