version: '2.0'

services:
  ros2_x11:
    image: ros:foxy-ros-base
    container_name: ros2_foxy
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - /home/pravaig/Documents/git/ros_ws:/home/ros_ws
    tty: true
    stdin_open: true
    command: bash
